### PR TITLE
Update data

### PR DESCRIPTION
**Pull request by seromenho**
To be used with Fliplet/fliplet-api/pull/850

### CODE REVIEW

**Comment by tonytlwu** [comment]
@seromenho Good stuff. Could you add this update to `fliplet-widget-advanced-directory` too?

**Review by tonytlwu — APPROVED** [review]

**Comment by seromenho** [comment]
@tonytlwu sure I can 😂 
https://github.com/Fliplet/fliplet-widget-advanced-directory/pull/3

**Comment by tonytlwu** [comment]
Wow. It's like you're from the future 😱

**Comment by seromenho** [comment]
Ahaha.
You approved this, but don't forget this only works with Fliplet/fliplet-api#850

**Comment by squallstar** [comment]
@seromenho @tonytlwu status update on this?

**Comment by hcarneiro** [comment]
@seromenho @tonytlwu What's the status of this?
In a couple of months it will be a year since the last comment on this PR.

**Comment by seromenho** [comment]
Closing this as it is outdated for sure 😄

**Comment by squallstar** [comment]
@seromenho I thought you would have finished this piece of work at some point!

**Comment by seromenho** [comment]
@squallstar nope. We didn't wen't with this direction. There was probably also a PR related to this on `fliplet-datasources` dependency to add this methods.
Then there was this changes on the local db and so on...

**Comment by squallstar** [comment]
@seromenho come on, that was a joke :) this PR is from January 2017, I'm pretty sure if we didn't get this done we don't need it.

**Comment by seromenho** [comment]
😂 😂 😂

**Pull request closed without merging**
