### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by hcarneiro**
Fixes: https://github.com/Fliplet/fliplet-studio/issues/1955
Other fixes too.

Validation for the following:
- Data source
- If chat enabled
  - Chat link
- If Add entries enabled
  - Add entries link
- If edit entries enabled
  - Edit entries link
- If thumbnails enabled
  - Thumbnails data source field
  - Thumbnails folder

Validation example:
screen shot 2018-01-05 at 11 44 35

### CODE REVIEW

**Comment by seromenho** [comment]
@hcarneiro The validation css/alerts could be a global feature so that it can be used by any widget.
What do you think?

**Comment by hcarneiro** [comment]
@seromenho Yes that would be cool. Keeping in mind that different widgets have different validations, as long as the system is flexible to let the developer choose what to validate and not.

Do you have anything in mind for such global system?

**Comment by seromenho** [comment]
@hcarneiro I didn't mean the validation validation but the styles and how to show it.
Just an idea from what you have done `Fliplet.Navigate.popup(options);`  we could for example pass an option class that will receive success,info,danger or some other class and add it to the popup div  on the options. And the styles be on a central place in the API

**Comment by hcarneiro** [comment]
@seromenho The `Fliplet.Navigate.popup(options);` is for the app side, is a just in case for some reason the validation doesn't work.

The validation error you see above in the screenshot is on the interface and happens on save with several checks, I don't use the `Fliplet.Navigate.popup(options);` there.

However a system like `Fliplet.Navigate.popup(options);` to display that alert within a widget interface would be nice. If that's what you are talking about then I'll create a feature proposed ticket for it with some specs.

**Comment by seromenho** [comment]
Ah yes. Realised that only after my own reply.
I think we need this finished: https://github.com/Fliplet/fliplet-api/pull/1800/files
Then we could `Fliplet.Modal.alert(options)`
calling @tonytlwu to the party

**Comment by hcarneiro** [comment]
@seromenho It could be something similar to that but that one is for Studio and appears in the centre on the screen and not in the context of the widget.

**Comment by seromenho** [comment]
@hcarneiro The idea is the same. It should appear in the centre of the screen at least this was what I got from Tony when I talked something with him regarding the Fliplet Modal on the API.
@tonytlwu to confirm.

**Comment by hcarneiro** [comment]
@seromenho Let's move the discussion here: https://github.com/Fliplet/fliplet-studio/issues/1964

**Review by tonytlwu — APPROVED** [review]

**Pull request merged**
